disabled_rules:
  - colon
  - todo
  - nesting
  - line_length
  - force_cast
  - comma
  - statement_position
  - multiple_closures_with_trailing_closure
  - private_outlet
  - trailing_whitespace
  - legacy_constructor

excluded: 
  - Carthage
  - Pods
  - External
  - Submodules
  - temporary
  - vendor
  - output
  - Kaidee Assignment/AppDelegate.swift
  - Kaidee Assignment/SceneDelegate.swift

# rule parameters
cyclomatic_complexity:
  - 50 #warning
  - 100 #error

file_length:
  - 600 #warning
  - 800 #error

function_body_length:
  - 100 #warning
  - 300 #error

line_length:
  - 300 #warning
  - 350 #error

type_body_length:
  - 400 #warning
  - 600 #error
file_length:
  warning: 500
  error: 2000
function_parameter_count:
  warning: 10
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
variable_name:
  min_length: 2 #warning
  max_length: #warning or error
    warning: 40
    error: 80
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
opt_in_rules:
 # - missing_docs
  - force_unwrapping
  - control_statement
  - private_outlet
  - vertical_whitespace
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
custom_rules:
  extra_whitespace:
    name: "Extra whitespaces"
    message: "Remove extra whitespaces"
    severity: warning
  comments_space:
    name: "Space After Comment"
    message: "There should be a space after //"
    severity: warning
  empty_first_line:
    name: "Empty First Line"
    message: "There should be an empty line after a declaration"
    severity: warning
  empty_line_after_guard:
    name: "Empty Line After Guard"
    message: "There should be an empty line after a guard"
    severity: warning
  empty_line_after_super:
    name: "Empty Line After Super"
    message: "There should be an empty line after super"
    severity: warning
  multiple_empty_lines:
    name: "Multiple Empty Lines"
    message: "There are too many empty lines"
    severity: warning
  unnecessary_leading_void_in:
    name: "Unnecessary -> Void in at the end of the line"
    message: "Unnecessary '-> Void in' at the end of the line. Use only 'in'"
    severity: warning
  unnecessary_type:
    name: "Unnecessary Type"
    message: "Type Definition Not Needed"
    severity: warning
  empty_closure_params:
    name: "Empty closure params"
    message: "`() -> Void in` should be avoided"
    severity: warning
  invalid_mark_format:
    name: "Invalid MARK Format"
    message: "Use format: MARK: - Your Info"
    severity: warning

